name: "MarsRoverKataTests"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        nix-shell --run 'pnpm install && pnpm test'
  mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - run: |
        brew install --cask docker virtualbox
        brew install docker-machine
        docker-machine create --driver virtualbox default
        docker-machine restart
        eval "$(docker-machine env default)"
        docker-machine regenerate-certs default
        docker-machine restart
        docker-compose run mac nix-shell --run 'pnpm test'
